version: "3.4"

services:
  app:
    build: .
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
volumes:
  node_modules: